name: Kotlin CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - run: ./gradlew -v
      - run: ./gradlew clean build
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: db2f30943b2979f9768f67b6c00a4f4f538ffa86ec37d5d7c536988618e500b8
        with:
          coverageCommand: ./gradlew jacocoTestReport