name: Kotlin CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: infrastructure version
      - run: ./gradlew -v
      - name: build
      - run: ./gradlew build --no-daemon
